const CREATE_POST = "CREATE_POST";
const DELETE_POST = "DELETE_POST";
const UPDATE_POST = "UPDATE_POST";
const GET_POSTS = "GET_POSTS";
const GET_POST = "GET_POST";

export { CREATE_POST, DELETE_POST, UPDATE_POST, GET_POST, GET_POSTS };
