const REGISTER_USER = "REGISTER_USER";
const UPDATE_USER = "UPDATE_USER";
const DELETE_USER = "DELETE_USER";
const GET_USER = "GET_USER";

export { REGISTER_USER, UPDATE_USER, DELETE_USER, GET_USER };
