const CREATE_POST = "CREATE_POST";
const UPDATE_POST = "UPDATE_POST";
const GET_ALL_POSTS = "GET_ALL_POSTS";
const GET_POST_BY_ID = "GET_POST_BY_ID";
const DELETE_POST = "DELETE_POST";

export { CREATE_POST, UPDATE_POST, GET_ALL_POSTS, GET_POST_BY_ID, DELETE_POST };
